language: android
sudo: true
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository

before_script: 
  git clone https://github.com/Tomicyo/kaleido3d_dep.git Source/ThirdParty
  
before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root

script: cd Project/android && ./gradlew build
