find_package(PythonInterp)
if(PYTHON_EXECUTABLE)
	execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "import yaml" RESULT_VARIABLE YAML_RET)
	if("0" STREQUAL "${YAML_RET}")
		message(STATUS "Python exists yaml")
	else()
		execute_process(COMMAND ${PYTHON_EXECUTABLE} -m pip install PyYaml RESULT_VARIABLE YAML_INSTALL_RET)
		if("0" STREQUAL "${YAML_INSTALL_RET}")
			message(STATUS "PyYaml Installed.")
		endif()
	endif()
	set(PY_YAML_FOUND TRUE)
else()
	message(WARNING "Python not Exists.")
	set(PY_YAML_FOUND FALSE)
endif()