TARGET = launcher
CONFIG -= QT
include (d:/lib/physx_x64.pri)
include (d:/lib/openal_x64.pri)
INCLUDEPATH+=\
	$$PWD/../../Include\
	$$PWD/../../Source/Renderer\
	$$PWD/../../Source
include (d:/lib/glfw_x64.pri)
DEFINES += USE_GLFW
PRECOMPILED_HEADER +=$$PWD/../../Include/Config/Prerequisities.h
HEADERS+=\
	../../Source/Renderer/k3dGPUBuffer.h\
	../../Source/Renderer/k3dRender.h\
	../../Source/Renderer/k3dRenderable.h\
	../../Source/Renderer/k3dRenderer.h\
	../../Source/Renderer/k3dRenderManager.h\
	../../Source/Renderer/k3dRenderMesh.h\
	../../Source/Renderer/k3dRenderNode.h\
	../../Source/Renderer/k3dRenderState.h\
	../../Source/Renderer/k3dRenderTexture.h\
	../../Source/Renderer/k3dShader.h\
	../../Source/Renderer/k3dTechnique.h\
	../../Source/Renderer/k3dTexture.h\
	../../Source/Renderer/RenderEnums.h\
	../../Source/Renderer/OpenGL/kGLBuffer.h\
	../../Source/Renderer/OpenGL/kGLBufferLockManager.h\
	../../Source/Renderer/OpenGL/kGLContext.h\
	../../Source/Renderer/OpenGL/kGLFrameBuffer.h\
	../../Source/Renderer/OpenGL/kGLMesh.h\
	../../Source/Renderer/OpenGL/kGLPipeline.h\
	../../Source/Renderer/OpenGL/kGLPostEffect.h\
	../../Source/Renderer/OpenGL/kGLRender.h\
	../../Source/Renderer/OpenGL/kGLRenderManager.h\
	../../Source/Renderer/OpenGL/kGLRenderState.h\
	../../Source/Renderer/OpenGL/kGLRenderTexture.h\
	../../Source/Renderer/OpenGL/kGLResourceManager.h\
	../../Source/Renderer/OpenGL/kGLSamplerObj.h\
	../../Source/Renderer/OpenGL/kGLSeperateShader.h\
	../../Source/Renderer/OpenGL/kGLShader.h\
	../../Source/Renderer/OpenGL/kGLShaderParameter.h\
	../../Source/Renderer/OpenGL/kGLSurface.h\
	../../Source/Renderer/OpenGL/kGLTechnique.h\
	../../Source/Renderer/OpenGL/kGLTexture.h\
	../../Source/Renderer/OpenGL/kGLUniformBuffer.h\
	../../Source/Renderer/OpenGL/kGLVertexBuffer.h\
	../../Source/Renderer/OpenGL/kGLWrapper.h\
	../../Source/Renderer/OpenGL/tGLBuffer.h\
	../../Source/Renderer/Postprocess/BokehDepthOfField.h\
	../../Source/Renderer/Postprocess/CascadeShadowMap.h\
	../../Source/Renderer/Postprocess/HighDynamicRendering.h\
	../../Source/Renderer/Postprocess/ScreenSpaceDirectionalOcclusion.h\
	../../Source/Renderer/Postprocess/ScreenSpaceReflection.h\
	../../Source/Audio/kAuEngine.h\
	../../Source/Core/k3dArchive.h\
	../../Source/Core/k3dDbg.h\
	../../Source/Core/k3dFile.h\
	../../Source/Core/k3dImage.h\
	../../Source/Core/k3dLog.h\
	../../Source/Core/k3dMaterial.h\
	../../Source/Core/k3dMesh.h\
	../../Source/Core/k3dTask.h\
	../../Source/Core/k3dTimer.h\
	../../Source/Core/k3dVariant.h\
	../../Source/Core/DDSHelper/DDSHelper.h\
	../../Source/Renderer/OpenGL/kGLBuffer.h\
	../../Source/Renderer/OpenGL/kGLBufferLockManager.h\
	../../Source/Renderer/OpenGL/kGLContext.h\
	../../Source/Renderer/OpenGL/kGLFrameBuffer.h\
	../../Source/Renderer/OpenGL/kGLMesh.h\
	../../Source/Renderer/OpenGL/kGLPipeline.h\
	../../Source/Renderer/OpenGL/kGLPostEffect.h\
	../../Source/Renderer/OpenGL/kGLRender.h\
	../../Source/Renderer/OpenGL/kGLRenderManager.h\
	../../Source/Renderer/OpenGL/kGLRenderState.h\
	../../Source/Renderer/OpenGL/kGLRenderTexture.h\
	../../Source/Renderer/OpenGL/kGLResourceManager.h\
	../../Source/Renderer/OpenGL/kGLSamplerObj.h\
	../../Source/Renderer/OpenGL/kGLSeperateShader.h\
	../../Source/Renderer/OpenGL/kGLShader.h\
	../../Source/Renderer/OpenGL/kGLShaderParameter.h\
	../../Source/Renderer/OpenGL/kGLSurface.h\
	../../Source/Renderer/OpenGL/kGLTechnique.h\
	../../Source/Renderer/OpenGL/kGLTexture.h\
	../../Source/Renderer/OpenGL/kGLUniformBuffer.h\
	../../Source/Renderer/OpenGL/kGLVertexBuffer.h\
	../../Source/Renderer/OpenGL/kGLWrapper.h\
	../../Source/Renderer/OpenGL/tGLBuffer.h\
	../../Source/Engine/k3dAssetManager.h\
	../../Source/Engine/k3dCamera.h\
	../../Source/Engine/k3dController.h\
	../../Source/Engine/k3dEngine.h\
	../../Source/Engine/k3dEngineContext.h\
	../../Source/Engine/k3dFollowCamera.h\
	../../Source/Engine/k3dFreeCamera.h\
	../../Source/Engine/k3dFrustum.h\
	../../Source/Engine/k3dLevelLoader.h\
	../../Source/Engine/k3dMaterialManager.h\
	../../Source/Engine/k3dModel.h\
	../../Source/Engine/k3dOctree.h\
	../../Source/Engine/k3dOctreeManager.h\
	../../Source/Engine/k3dPostEffect.h\
	../../Source/Engine/k3dSceneManager.h\
	../../Source/Engine/k3dSceneObject.h\
	../../Source/Engine/k3dSplashScreen.h\
	../../Source/Engine/k3dTargetCamera.h\
	../../Source/Engine/kDebugDrawUtils.h\
	../../Source/Entity/k3dLight.h\
	../../Source/Entity/k3dLightDirectional.h\
	../../Source/Entity/k3dLightManger.h\
	../../Source/Entity/k3dLightOmni.h\
	../../Source/Entity/k3dLightProbe.h\
	../../Source/Entity/k3dLightSpot.h\
	../../Source/Entity/k3dMoveable.h\
	../../Source/Entity/k3dSky.h\
	../../Source/Entity/k3dStaticObject.h\
	../../Source/Entity/k3dTerrain.h\
	../../Source/Entity/k3dVehicle.h\
	../../Source/Entity/k3dVehicleController.h\
	../../Source/Entity/k3dVehicleWheel.h\
	../../Source/Entity/k3dWater.h\
	../../Source/Physics/k3dVehicleManager.h\
	../../Source/Physics/kPsEngine.h\
	../../Source/Physics/kVehicleRaycast.h\
	../../Source/Physics/kVehicleSceneQuery.h\
	../../Source/Physics/PxSupport.h
SOURCES+=\
	../../Source/Renderer/k3dGPUBuffer.cpp\
	../../Source/Renderer/k3dRender.cpp\
	../../Source/Renderer/k3dRenderable.cpp\
	../../Source/Renderer/k3dRenderer.cpp\
	../../Source/Renderer/k3dRenderManager.cpp\
	../../Source/Renderer/k3dRenderMesh.cpp\
	../../Source/Renderer/k3dRenderNode.cpp\
	../../Source/Renderer/k3dRenderTexture.cpp\
	../../Source/Renderer/k3dShader.cpp\
	../../Source/Renderer/k3dTechnique.cpp\
	../../Source/Renderer/OpenGL/kGLBuffer.cpp\
	../../Source/Renderer/OpenGL/kGLBufferLockManager.cpp\
	../../Source/Renderer/OpenGL/kGLContext.cpp\
	../../Source/Renderer/OpenGL/kGLFrameBuffer.cpp\
	../../Source/Renderer/OpenGL/kGLMesh.cpp\
	../../Source/Renderer/OpenGL/kGLPipeline.cpp\
	../../Source/Renderer/OpenGL/kGLPostEffect.cpp\
	../../Source/Renderer/OpenGL/kGLRender.cpp\
	../../Source/Renderer/OpenGL/kGLRenderManager.cpp\
	../../Source/Renderer/OpenGL/kGLRenderState.cpp\
	../../Source/Renderer/OpenGL/kGLRenderTexture.cpp\
	../../Source/Renderer/OpenGL/kGLResourceManager.cpp\
	../../Source/Renderer/OpenGL/kGLSamplerObj.cpp\
	../../Source/Renderer/OpenGL/kGLSeperateShader.cpp\
	../../Source/Renderer/OpenGL/kGLShader.cpp\
	../../Source/Renderer/OpenGL/kGLShaderParameter.cpp\
	../../Source/Renderer/OpenGL/kGLSurface.cpp\
	../../Source/Renderer/OpenGL/kGLTechnique.cpp\
	../../Source/Renderer/OpenGL/kGLTexture.cpp\
	../../Source/Renderer/OpenGL/kGLUniformBuffer.cpp\
	../../Source/Renderer/OpenGL/kGLVertexBuffer.cpp\
	../../Source/Renderer/OpenGL/kGLWrapper.cpp\
	../../Source/Renderer/OpenGL/tGLBuffer.cpp\
	../../Source/Renderer/Postprocess/BokehDepthOfField.cpp\
	../../Source/Renderer/Postprocess/CascadeShadowMap.cpp\
	../../Source/Renderer/Postprocess/HighDynamicRendering.cpp\
	../../Source/Renderer/Postprocess/ScreenSpaceDirectionalOcclusion.cpp\
	../../Source/Renderer/Postprocess/ScreenSpaceReflection.cpp\
	../../Source/Audio/kAuEngine.cpp\
	../../Source/Core/k3dArchive.cpp\
	../../Source/Core/k3dDbg.cpp\
	../../Source/Core/k3dFile.cpp\
	../../Source/Core/k3dImage.cpp\
	../../Source/Core/k3dLog.cpp\
	../../Source/Core/k3dMaterial.cpp\
	../../Source/Core/k3dMesh.cpp\
	../../Source/Core/k3dTask.cpp\
	../../Source/Core/k3dTimer.cpp\
	../../Source/Core/DDSHelper/DDSHelper.cpp\
	../../Source/Renderer/OpenGL/kGLBuffer.cpp\
	../../Source/Renderer/OpenGL/kGLBufferLockManager.cpp\
	../../Source/Renderer/OpenGL/kGLContext.cpp\
	../../Source/Renderer/OpenGL/kGLFrameBuffer.cpp\
	../../Source/Renderer/OpenGL/kGLMesh.cpp\
	../../Source/Renderer/OpenGL/kGLPipeline.cpp\
	../../Source/Renderer/OpenGL/kGLPostEffect.cpp\
	../../Source/Renderer/OpenGL/kGLRender.cpp\
	../../Source/Renderer/OpenGL/kGLRenderManager.cpp\
	../../Source/Renderer/OpenGL/kGLRenderState.cpp\
	../../Source/Renderer/OpenGL/kGLRenderTexture.cpp\
	../../Source/Renderer/OpenGL/kGLResourceManager.cpp\
	../../Source/Renderer/OpenGL/kGLSamplerObj.cpp\
	../../Source/Renderer/OpenGL/kGLSeperateShader.cpp\
	../../Source/Renderer/OpenGL/kGLShader.cpp\
	../../Source/Renderer/OpenGL/kGLShaderParameter.cpp\
	../../Source/Renderer/OpenGL/kGLSurface.cpp\
	../../Source/Renderer/OpenGL/kGLTechnique.cpp\
	../../Source/Renderer/OpenGL/kGLTexture.cpp\
	../../Source/Renderer/OpenGL/kGLUniformBuffer.cpp\
	../../Source/Renderer/OpenGL/kGLVertexBuffer.cpp\
	../../Source/Renderer/OpenGL/kGLWrapper.cpp\
	../../Source/Renderer/OpenGL/tGLBuffer.cpp\
	../../Source/Engine/k3dAssetManager.cpp\
	../../Source/Engine/k3dCamera.cpp\
	../../Source/Engine/k3dController.cpp\
	../../Source/Engine/k3dEngine.cpp\
	../../Source/Engine/k3dFollowCamera.cpp\
	../../Source/Engine/k3dFreeCamera.cpp\
	../../Source/Engine/k3dFrustum.cpp\
	../../Source/Engine/k3dLevelLoader.cpp\
	../../Source/Engine/k3dMaterialManager.cpp\
	../../Source/Engine/k3dModel.cpp\
	../../Source/Engine/k3dOctree.cpp\
	../../Source/Engine/k3dOctreeManager.cpp\
	../../Source/Engine/k3dPostEffect.cpp\
	../../Source/Engine/k3dSceneManager.cpp\
	../../Source/Engine/k3dSplashScreen.cpp\
	../../Source/Engine/k3dTargetCamera.cpp\
	../../Source/Engine/kDebugDrawUtils.cpp\
	../../Source/Engine/kSceneCore.cpp\
	../../Source/Entity/k3dLight.cpp\
	../../Source/Entity/k3dLightDirectional.cpp\
	../../Source/Entity/k3dLightManger.cpp\
	../../Source/Entity/k3dLightOmni.cpp\
	../../Source/Entity/k3dLightProbe.cpp\
	../../Source/Entity/k3dLightSpot.cpp\
	../../Source/Entity/k3dMoveable.cpp\
	../../Source/Entity/k3dSky.cpp\
	../../Source/Entity/k3dStaticObject.cpp\
	../../Source/Entity/k3dTerrain.cpp\
	../../Source/Entity/k3dVehicle.cpp\
	../../Source/Entity/k3dVehicleController.cpp\
	../../Source/Entity/k3dVehicleWheel.cpp\
	../../Source/Entity/k3dWater.cpp\
	../../Source/Physics/k3dVehicleManager.cpp\
	../../Source/Physics/kPsEngine.cpp\
	../../Source/Physics/kVehicleRaycast.cpp\
	../../Source/Physics/kVehicleSceneQuery.cpp
CONFIG += c++11
DEFINES += ENABLE_SSE
win32: RC_FILE = ../../Project/kaleido3d.rc
